import { useEffect, useState } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import { BarChart3, BookOpen, Home, Pencil, Plus, Search, Settings, Tags, Trash2, WalletCards, X } from 'lucide-react'
import type { AppSettings, CategoryGroup, Expense, NewExpense, OperationResult } from '../../shared/types'
import { categories as initialCategories, categoryEmoji } from './categories'
import appIcon from '../../../build/icon.png'

const navItems=[{label:'首页',icon:Home},{label:'流水',icon:BookOpen},{label:'统计',icon:BarChart3},{label:'分类',icon:Tags},{label:'设置',icon:Settings}]
const paymentMethods=['微信支付','支付宝','银行卡','现金','其他']
const money=(c:number)=>`¥${(c/100).toFixed(2)}`
const monthKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`
const monthLabel=(key:string)=>{const [y,m]=key.split('-');return `${y}年${Number(m)}月`}
const localDateTime=(iso?:string)=>{const d=iso?new Date(iso):new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
const groupByCategory=(items:Expense[]):[string,number][]=>Object.entries(items.reduce<Record<string,number>>((r,x)=>{r[x.primaryCategory]=(r[x.primaryCategory]??0)+x.amountInCents;return r},{})).sort((a,b)=>b[1]-a[1])

export default function App(){
  const [expenses,setExpenses]=useState<Expense[]>([]),[active,setActive]=useState('首页'),[open,setOpen]=useState(false),[editing,setEditing]=useState<Expense|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const [settings,setSettings]=useState<AppSettings>({theme:'system',defaultPaymentMethod:'微信支付'})
  const [categoryGroups,setCategoryGroups]=useState<CategoryGroup[]>([])
  const load=async()=>{try{const [items,options,groups]=await Promise.all([window.ledger.listExpenses(),window.ledger.getSettings(),window.ledger.listCategories()]);setExpenses(items);setSettings(options);setCategoryGroups(groups)}catch{setError('数据读取失败，请重新启动应用')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  useEffect(()=>{document.documentElement.dataset.theme=settings.theme},[settings.theme])
  const now=new Date(),thisMonth=expenses.filter(x=>x.occurredAt.startsWith(monthKey(now))),previousMonth=expenses.filter(x=>x.occurredAt.startsWith(monthKey(new Date(now.getFullYear(),now.getMonth()-1,1)))),total=thisMonth.reduce((s,x)=>s+x.amountInCents,0),previousTotal=previousMonth.reduce((s,x)=>s+x.amountInCents,0)
  const catalog=categoryGroups.length?Object.fromEntries(categoryGroups.filter(x=>x.enabled).map(x=>[x.name,x.children.filter(child=>child.enabled).map(child=>child.name)]).filter(([,children])=>(children as string[]).length)):initialCategories
  const add=()=>{setEditing(null);setOpen(true)},edit=(x:Expense)=>{setEditing(x);setOpen(true)}
  const remove=async(x:Expense)=>{if(!confirm(`确定删除 ${money(x.amountInCents)} 的${x.secondaryCategory}花销吗？`))return;await window.ledger.deleteExpense(x.id);await load()}
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><img className="brand-image" src={appIcon} alt="可噜记账"/><div><strong>可噜记账</strong><small>把每一笔，都记得明白</small></div></div><nav>{navItems.map(({label,icon:Icon})=><button key={label} className={active===label?'active':''} onClick={()=>setActive(label)}><Icon size={19}/>{label}</button>)}</nav><div className="privacy-note"><WalletCards size={20}/><div><strong>数据安心存在本机</strong><span>无需账号，离线也能使用</span></div></div></aside><main><header><div><p className="eyebrow">{new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</p><h1>{active==='首页'?'今天，也要好好生活':active}</h1></div><button className="primary" onClick={add}><Plus size={19}/>记一笔</button></header>{active==='首页'?<HomePage expenses={expenses} current={thisMonth} total={total} previousTotal={previousTotal} loading={loading} go={()=>setActive('流水')} edit={edit} remove={remove}/>:active==='流水'?<LedgerPage expenses={expenses} loading={loading} edit={edit} remove={remove} catalog={catalog}/>:active==='统计'?<StatisticsPage expenses={expenses}/>:active==='分类'?<CategoriesPage groups={categoryGroups} reload={load}/>:active==='设置'?<SettingsPage settings={settings} onSettings={setSettings} onReload={load}/>:null}{error&&<div className="error-toast">{error}</div>}</main><ExpenseDialog open={open} onOpenChange={setOpen} onSaved={load} expense={editing} defaultPayment={settings.defaultPaymentMethod} catalog={catalog}/></div>
}

function HomePage({expenses,current,total,previousTotal,loading,go,edit,remove}:{expenses:Expense[];current:Expense[];total:number;previousTotal:number;loading:boolean;go:()=>void;edit:(x:Expense)=>void;remove:(x:Expense)=>void}){const change=previousTotal?Math.round((total-previousTotal)/previousTotal*100):null;return <><section className="hero-card"><div><span>本月累计支出</span><strong>{money(total)}</strong><p>{current.length?`共记录 ${current.length} 笔花销${change===null?'，上月暂无对比数据':`，较上月${change>0?'增加':'减少'} ${Math.abs(change)}%`}`:'从记录第一笔花销开始吧'}</p></div><div className="horse-art">♞</div></section><div className="content-grid"><section className="panel"><div className="section-title"><h2>最近花销</h2><button onClick={go}>查看全部</button></div><ExpenseList expenses={expenses.slice(0,6)} loading={loading} edit={edit} remove={remove}/></section><section className="panel"><div className="section-title"><h2>分类概览</h2><span>本月</span></div><CategoryBars grouped={groupByCategory(current)}/></section></div></>}

function LedgerPage({expenses,loading,edit,remove,catalog}:{expenses:Expense[];loading:boolean;edit:(x:Expense)=>void;remove:(x:Expense)=>void;catalog:Record<string,string[]>}){
  const [query,setQuery]=useState(''),[primary,setPrimary]=useState('全部'),[payment,setPayment]=useState('全部'),[month,setMonth]=useState('全部')
  const months=Array.from(new Set(expenses.map(x=>x.occurredAt.slice(0,7)))).sort().reverse()
  const filtered=expenses.filter(x=>(month==='全部'||x.occurredAt.startsWith(month))&&(primary==='全部'||x.primaryCategory===primary)&&(payment==='全部'||x.paymentMethod===payment)&&(!query||`${x.merchant} ${x.note} ${x.primaryCategory} ${x.secondaryCategory}`.toLowerCase().includes(query.toLowerCase())))
  const clear=()=>{setQuery('');setPrimary('全部');setPayment('全部');setMonth('全部')}
  return <section className="panel page-panel"><div className="section-title"><h2>全部流水</h2><span>{filtered.length} / {expenses.length} 笔</span></div><div className="filters"><label className="search-box"><Search size={16}/><input placeholder="搜索商家、备注或分类" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={month} onChange={e=>setMonth(e.target.value)}><option>全部</option>{months.map(x=><option key={x} value={x}>{monthLabel(x)}</option>)}</select><select value={primary} onChange={e=>setPrimary(e.target.value)}><option>全部</option>{Object.keys(catalog).map(x=><option key={x}>{x}</option>)}</select><select value={payment} onChange={e=>setPayment(e.target.value)}><option>全部</option>{paymentMethods.map(x=><option key={x}>{x}</option>)}</select><button className="filter-clear" onClick={clear}>清除</button></div><ExpenseList expenses={filtered} loading={loading} edit={edit} remove={remove}/></section>
}

function StatisticsPage({expenses}:{expenses:Expense[]}){
  const available=Array.from(new Set([monthKey(new Date()),...expenses.map(x=>x.occurredAt.slice(0,7))])).sort().reverse(),[selected,setSelected]=useState(available[0])
  const current=expenses.filter(x=>x.occurredAt.startsWith(selected)),[year,month]=selected.split('-').map(Number),previousKey=monthKey(new Date(year,month-2,1)),previous=expenses.filter(x=>x.occurredAt.startsWith(previousKey)),total=current.reduce((s,x)=>s+x.amountInCents,0),previousTotal=previous.reduce((s,x)=>s+x.amountInCents,0),difference=total-previousTotal,percent=previousTotal?Math.round(difference/previousTotal*100):null,days=new Date(year,month,0).getDate(),daily=Array.from({length:days},(_,i)=>current.filter(x=>new Date(x.occurredAt).getDate()===i+1).reduce((s,x)=>s+x.amountInCents,0)),max=Math.max(...daily,1),grouped=groupByCategory(current)
  return <div className="stats-page"><div className="stats-toolbar"><select value={selected} onChange={e=>setSelected(e.target.value)}>{available.map(x=><option key={x} value={x}>{monthLabel(x)}</option>)}</select></div><div className="stat-cards"><section className="panel stat-card"><span>本月总支出</span><strong>{money(total)}</strong><small>{current.length} 笔花销</small></section><section className="panel stat-card"><span>较上月变化</span><strong className={difference>0?'up':'down'}>{difference>0?'+':''}{money(difference)}</strong><small>{percent===null?'上月暂无支出':`${percent>0?'+':''}${percent}%`}</small></section><section className="panel stat-card"><span>日均支出</span><strong>{money(Math.round(total/days))}</strong><small>按自然月计算</small></section></div><div className="stats-grid"><section className="panel"><div className="section-title"><h2>每日趋势</h2><span>{monthLabel(selected)}</span></div><div className="daily-chart">{daily.map((value,i)=><div key={i} title={`${i+1}日 ${money(value)}`}><i style={{height:`${Math.max(value?5:1,value/max*100)}%`}}/><span>{(i+1)%5===0||i===0?i+1:''}</span></div>)}</div></section><section className="panel"><div className="section-title"><h2>分类占比</h2><span>{grouped.length} 类</span></div><CategoryBars grouped={grouped}/></section></div></div>
}

function SettingsPage({settings,onSettings,onReload}:{settings:AppSettings;onSettings:(x:AppSettings)=>void;onReload:()=>Promise<void>}){
  const [status,setStatus]=useState('')
  const [dataLocation,setDataLocation]=useState('正在读取…')
  useEffect(()=>{void window.ledger.getDataLocation().then(setDataLocation)},[])
  const save=async(next:AppSettings)=>{const saved=await window.ledger.saveSettings(next);onSettings(saved);setStatus('设置已保存')}
  const run=async(action:()=>Promise<OperationResult>,reload=false)=>{try{setStatus('正在处理…');const result=await action();setStatus(result.message);if(result.success&&reload)await onReload()}catch{setStatus('操作失败，当前数据没有改变')}}
  const importCsv=async()=>{try{setStatus('正在检查文件…');const preview=await window.ledger.previewImportCsv();if(preview.canceled){setStatus(preview.message);return}if(!preview.success){setStatus(`${preview.message}${preview.errorDetails.length?`：${preview.errorDetails.join('；')}`:''}`);return}const details=`可导入 ${preview.valid} 笔，重复 ${preview.duplicates} 笔，错误 ${preview.errors} 笔。${preview.errorDetails.length?`\n\n${preview.errorDetails.join('\n')}`:''}`;if(!preview.valid){setStatus(details);return}if(confirm(`${details}\n\n确认导入有效记录吗？`)){await run(()=>window.ledger.confirmImportCsv(),true)}else setStatus('已取消写入，当前数据没有改变')}catch{setStatus('文件检查失败，当前数据没有改变')}}
  const restore=()=>{if(confirm('恢复备份会替换当前账目。系统会先自动保存当前数据，确定继续吗？'))void run(()=>window.ledger.restoreBackup(),true)}
  const changeLocation=async()=>{try{setStatus('正在安全迁移账目…');const result=await window.ledger.changeDataLocation();setStatus(result.message);if(result.path)setDataLocation(result.path);if(result.success)await onReload()}catch{setStatus('迁移失败，当前数据位置没有改变')}}
  return <div className="settings-page"><section className="panel settings-section"><div className="section-title"><h2>外观与记账偏好</h2><span>自动保存</span></div><div className="setting-row"><div><strong>主题模式</strong><p>选择最适合你的显示方式</p></div><select value={settings.theme} onChange={e=>void save({...settings,theme:e.target.value as AppSettings['theme']})}><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></div><div className="setting-row"><div><strong>默认支付方式</strong><p>新增花销时会自动选中</p></div><select value={settings.defaultPaymentMethod} onChange={e=>void save({...settings,defaultPaymentMethod:e.target.value})}>{paymentMethods.map(x=><option key={x}>{x}</option>)}</select></div></section><section className="panel settings-section"><div className="section-title"><h2>数据管理</h2><span>数据仅保存在本机</span></div><div className="data-location"><div><strong>账目存放位置</strong><code title={dataLocation}>{dataLocation}</code><small>更改时会迁移现有账目，原文件保留为安全备份</small></div><button className="secondary" onClick={()=>void changeLocation()}>更改位置</button></div><div className="data-actions"><button onClick={()=>void run(()=>window.ledger.exportCsv())}><strong>导出 CSV</strong><span>用表格软件查看全部流水</span></button><button onClick={()=>void importCsv()}><strong>导入 CSV</strong><span>先预览有效、重复和错误记录</span></button><button onClick={()=>void run(()=>window.ledger.createBackup())}><strong>创建完整备份</strong><span>保存账目、设置和全部数据</span></button><button className="danger-outline" onClick={restore}><strong>恢复完整备份</strong><span>用备份替换当前数据</span></button></div>{status&&<p className="operation-status">{status}</p>}</section><section className="panel settings-section privacy-card"><strong>隐私说明</strong><p>可噜记账无需账号，账目不会上传到云端。更换电脑或重装系统前，请主动创建完整备份。</p></section></div>
}

function CategoriesPage({groups,reload}:{groups:CategoryGroup[];reload:()=>Promise<void>}){
  const [status,setStatus]=useState('')
  const act=async(action:()=>Promise<OperationResult>)=>{const result=await action();setStatus(result.message);if(result.success)await reload()}
  const addPrimary=()=>{const name=prompt('请输入新的一级分类名称');if(name)void act(()=>window.ledger.addCategory(null,name))}
  const addChild=(id:string)=>{const name=prompt('请输入新的二级分类名称');if(name)void act(()=>window.ledger.addCategory(id,name))}
  const rename=(id:string,current:string)=>{const name=prompt('请输入新的分类名称',current);if(name&&name!==current)void act(()=>window.ledger.renameCategory(id,name))}
  const remove=(id:string,name:string)=>{if(confirm(`确定删除“${name}”吗？已有历史账目的分类不会被删除。`))void act(()=>window.ledger.deleteCategory(id))}
  return <section className="panel page-panel categories-page"><div className="section-title"><div><h2>两级分类管理</h2><p>停用不会影响历史账目和统计</p></div><button className="primary small" onClick={addPrimary}><Plus size={16}/>新增一级分类</button></div>{status&&<p className="operation-status">{status}</p>}<div className="category-groups">{groups.map(group=><article key={group.id} className={!group.enabled?'disabled':''}><div className="category-head"><div><span className="expense-icon">{categoryEmoji[group.name]??'✨'}</span><strong>{group.name}</strong><small>{group.children.length} 个二级分类</small></div><div className="category-actions"><button onClick={()=>void act(()=>window.ledger.moveCategory(group.id,'up'))}>↑</button><button onClick={()=>void act(()=>window.ledger.moveCategory(group.id,'down'))}>↓</button><button onClick={()=>rename(group.id,group.name)}>改名</button><button onClick={()=>void act(()=>window.ledger.toggleCategory(group.id,!group.enabled))}>{group.enabled?'停用':'启用'}</button>{!group.isDefault&&<button className="danger-text" onClick={()=>remove(group.id,group.name)}>删除</button>}<button onClick={()=>addChild(group.id)}>+ 二级分类</button></div></div><div className="category-children">{group.children.map(child=><div key={child.id} className={!child.enabled?'disabled':''}><span>{child.name}</span><div><button onClick={()=>void act(()=>window.ledger.moveCategory(child.id,'up'))}>↑</button><button onClick={()=>void act(()=>window.ledger.moveCategory(child.id,'down'))}>↓</button><button onClick={()=>rename(child.id,child.name)}>改名</button><button onClick={()=>void act(()=>window.ledger.toggleCategory(child.id,!child.enabled))}>{child.enabled?'停用':'启用'}</button>{!child.isDefault&&<button className="danger-text" onClick={()=>remove(child.id,child.name)}>删除</button>}</div></div>)}</div></article>)}</div></section>
}

function CategoryBars({grouped}:{grouped:[string,number][]}){return grouped.length?<div className="category-bars">{grouped.slice(0,7).map(([name,value])=><div key={name}><div><span>{categoryEmoji[name]} {name}</span><strong>{money(value)}</strong></div><i><b style={{width:`${Math.max(8,value/grouped[0][1]*100)}%`}}/></i></div>)}</div>:<Empty message="这个月还没有可统计的花销"/>}
function ExpenseList({expenses,loading,edit,remove}:{expenses:Expense[];loading:boolean;edit:(x:Expense)=>void;remove:(x:Expense)=>void}){if(loading)return <Empty message="正在读取账目…"/>;if(!expenses.length)return <Empty message="没有找到符合条件的账目"/>;return <div className="expense-list">{expenses.map(x=><article key={x.id}><span className="expense-icon">{categoryEmoji[x.primaryCategory]??'✨'}</span><div className="expense-main"><strong>{x.secondaryCategory}</strong><span>{x.merchant||x.note||x.primaryCategory} · {x.paymentMethod}</span></div><time>{new Date(x.occurredAt).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}</time><b>-{money(x.amountInCents)}</b><div className="row-actions"><button aria-label="编辑" onClick={()=>edit(x)}><Pencil size={15}/></button><button aria-label="删除" onClick={()=>void remove(x)}><Trash2 size={15}/></button></div></article>)}</div>}
function Empty({message}:{message:string}){return <div className="empty"><span>✦</span><p>{message}</p></div>}

function ExpenseDialog({open,onOpenChange,onSaved,expense,defaultPayment,catalog}:{open:boolean;onOpenChange:(v:boolean)=>void;onSaved:()=>Promise<void>;expense:Expense|null;defaultPayment:string;catalog:Record<string,string[]>}){
  const [amount,setAmount]=useState(''),[primary,setPrimary]=useState('餐饮'),[secondary,setSecondary]=useState('早餐'),[occurredAt,setOccurredAt]=useState(localDateTime()),[merchant,setMerchant]=useState(''),[note,setNote]=useState(''),[paymentMethod,setPaymentMethod]=useState('微信支付'),[saving,setSaving]=useState(false),[formError,setFormError]=useState('')
  useEffect(()=>{if(!open)return;setAmount(expense?(expense.amountInCents/100).toFixed(2):'');setPrimary(expense?.primaryCategory??'餐饮');setSecondary(expense?.secondaryCategory??'早餐');setOccurredAt(localDateTime(expense?.occurredAt));setMerchant(expense?.merchant??'');setNote(expense?.note??'');setPaymentMethod(expense?.paymentMethod||defaultPayment);setFormError('')},[open,expense,defaultPayment])
  const changePrimary=(v:string)=>{setPrimary(v);setSecondary(catalog[v][0])}
  const save=async(e:React.FormEvent)=>{e.preventDefault();const cents=Math.round(Number(amount)*100);if(!amount||!Number.isFinite(cents)||cents<=0||!/^\d+(\.\d{1,2})?$/.test(amount)){setFormError('请输入大于 0、最多两位小数的金额');return}const record:NewExpense={amountInCents:cents,primaryCategory:primary,secondaryCategory:secondary,occurredAt:new Date(occurredAt).toISOString(),note:note.trim(),paymentMethod,merchant:merchant.trim()};try{setSaving(true);setFormError('');if(expense)await window.ledger.updateExpense(expense.id,record);else await window.ledger.createExpense(record);await onSaved();onOpenChange(false)}catch{setFormError('保存失败，请检查填写内容后重试')}finally{setSaving(false)}}
  const selectedChildren=catalog[primary]??[secondary]
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content"><div className="dialog-heading"><div><Dialog.Title>{expense?'编辑花销':'记一笔花销'}</Dialog.Title><Dialog.Description>{expense?'修改后会立即更新统计结果。':'生活的每一笔，都值得被认真记录。'}</Dialog.Description></div><Dialog.Close className="icon-button"><X size={20}/></Dialog.Close></div><form onSubmit={save}><label className="amount-field"><span>花了多少钱</span><div><i>¥</i><input autoFocus inputMode="decimal" placeholder="0.00" value={amount} onChange={e=>setAmount(e.target.value)}/></div></label><div className="form-grid"><label>一级分类<select value={primary} onChange={e=>changePrimary(e.target.value)}>{Object.keys(catalog).map(x=><option key={x}>{x}</option>)}</select></label><label>二级分类<select value={secondary} onChange={e=>setSecondary(e.target.value)}>{selectedChildren.map(x=><option key={x}>{x}</option>)}</select></label><label>日期时间<input type="datetime-local" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)}/></label><label>支付方式<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}>{paymentMethods.map(x=><option key={x}>{x}</option>)}</select></label><label>商家（选填）<input placeholder="例如：街角咖啡店" value={merchant} onChange={e=>setMerchant(e.target.value)}/></label><label>备注（选填）<input placeholder="写点什么…" value={note} onChange={e=>setNote(e.target.value)}/></label></div>{formError&&<p className="form-error">{formError}</p>}<div className="dialog-actions"><Dialog.Close type="button" className="secondary">取消</Dialog.Close><button className="primary" disabled={saving}>{saving?'正在保存…':expense?'保存修改':'保存这笔花销'}</button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>
}
